4/24/15

diff --git a/bin/pamw b/bin/pamw
--- a/bin/pamw
+++ b/bin/pamw
@@ -1,45 +1,44 @@
 #!/bin/bash
-#
-# pamixer wrapper
 
 usage() {
-	echo "Usage: $(basename $0)	-g --get"
-	echo " 	 	-s --set VALUE"
-	echo " 	 	-i --inc PERCENTS"
-	echo " 	 	-d --dec PERCENTS"
+	echo "Usage: $(basename $0) <command>"
+	echo " -g --get		Get volume"
+	echo " -s --set VALUE		Set volume"
+	echo " -i --inc PERCENTS	Increase volume"
+	echo " -d --dec PERCENTS	Decrease volume"
+	echo " --gm			Get mute"
+	echo " -t --tog		Toggle mute"
+	echo " -u -unm		Unmute"
+	echo " -m --mut		Mute"
 }
-
-get() {
-	pamixer --get-volume
-}
-
-set() {
-	[[ -z "$1" ]] && pamixer --set-volume "$1"
-}
-
-inc() {
-	[[ -z "$1" ]] && pamixer --increase "$1"
-}
-
-dec() {
-	[[ -z "$1" ]] && pamixer --decrease "$1"
-}
-
-case $# in
-	0) get ;;
-	1)
-		case "$1" in
-			"-g"|"--get") get ;;
-			           *) usage ;;
-		esac
-		;;
-	2)
-		case "$1" in
-			'-s'|'--set') set "$2" ;;
-			'-i'|'--inc') inc "$2" ;;
-			'-d'|'--dec') dec "$2" ;;
-			           *) usage ;;
-		esac
-		;;
-	*) usage ;;
-esac
+if [[ -z $1 ]]; then
+	pamw -g
+else
+	case $1 in
+		'-s'|'--set')
+			[[ -n $2 ]] && pamixer --set-volume $2 || echo "missing argument"
+			;;
+		'-g'|'--get')
+			pamixer --get-volume
+			;;
+		'-i'|'--inc')
+			[[ -n $2 ]] && pamixer --increase $2 || echo "missing argument"
+			;;
+		'-d'|'--dec')
+			[[ -n $2 ]] && pamixer --decrease $2 || echo "missing argument"
+			;;
+		'--gm')
+			pamixer --get-mute
+			;;
+		'-t'|'--tog')
+			pamixer --toggle-mute
+			;;
+		'-u'|'--unm')
+			pamixer --unmute
+			;;
+		'-m'|'--mut')
+			pamixer --mute
+			;;
+		*) usage ;;
+	esac
+fi
